<?php
/* =====================================================================
    Constants (SideCI requirements)
   ================================================================== */
define('IS_ITEM_PRIVATE', true); // Qiita記事が限定共有状態
define('ID_ITEM_GITHUB_DUMMY', '1a52282f0b132347c2b1');
define('ID_ITEM_QIITA_DUMMY', '58ca66a808aa774c8233');
define('URL_BASE_GITHUB', 'https://raw.githubusercontent.com/Qithub-BOT/items/master/');
define('URL_BASE_QITHUB', 'https://qiita.com/api/v2/items/');
define('MAX_TAG_NUM_QIITA', 5);

/*
    IS_ENV_DEV は functions の set_env_as_dev() 内で設定されています。
*/
